version: "3.2"
services:
  web:
    build:
      context: './docker/web/'
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    ports:
      - 80
    volumes:
      - ./app/web/:/var/www/html/
  php:
    build:
      context: './docker/php/'
    networks:
      - frontend
      - backend
    volumes:
      - ./app/web/:/var/www/html/
    external_links:
      - web:$APP_HOSTNAME.local
  db:
    build:
      context: './docker/db/'
    networks:
      - backend
    volumes:
      - ./app/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
networks:
  frontend:
  backend:
