version: "3.2"
services:
  php:
    build:
      context: './docker/php/'
    networks:
      - backend
    volumes:
      - ./app/web/:/var/www/html/
  web_server:
    build:
      context: './docker/web/'
    depends_on:
      - php
      - database_server
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./app/web/:/var/www/html/
  database_server:
    build:
      context: './docker/db/'
    networks:
      - backend
    volumes:
      - ./app/db:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
networks:
  frontend:
  backend: